name: automatic deploy
on:
  push:
    branches:
      - master
    tags:
      - "!*"
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: npm run build